Answer.create!(:text => "“Tweeting.”")
Answer.create!(:text => "72 virgins.")
Answer.create!(:text => "8 oz. of sweet Mexican black-tar heroin.")
Answer.create!(:text => "A 55-gallon drum of lube.")
Answer.create!(:text => "A bag of magic beans.")
Answer.create!(:text => "A balanced breakfast.")
Answer.create!(:text => "A beached whale.")
Answer.create!(:text => "A big black dick.")
Answer.create!(:text => "A big hoopla about nothing.")
Answer.create!(:text => "A bigger, blacker dick.")
Answer.create!(:text => "A bleached asshole.")
Answer.create!(:text => "A bloody pacifier.")
Answer.create!(:text => "A Bop It.")
Answer.create!(:text => "A brain tumor.")
Answer.create!(:text => "A Burmese tiger pit.")
Answer.create!(:text => "A can of whoop-ass.")
Answer.create!(:text => "A Christmas stocking full of coleslaw.")
Answer.create!(:text => "A clandestine butt scratch.")
Answer.create!(:text => "A cooler full of organs.")
Answer.create!(:text => "A crappy little hand.")
Answer.create!(:text => "A death ray.")
Answer.create!(:text => "A defective condom.")
Answer.create!(:text => "A disappointing birthday party.")
Answer.create!(:text => "A dollop of sour cream.")
Answer.create!(:text => "A drive-by shooting.")
Answer.create!(:text => "A falcon with a cap on its head.")
Answer.create!(:text => "A fetus.")
Answer.create!(:text => "A foul mouth.")
Answer.create!(:text => "A gassy antelope.")
Answer.create!(:text => "A gentle caress of the inner thigh.")
Answer.create!(:text => "A good sniff.")
Answer.create!(:text => "A Gypsy curse.")
Answer.create!(:text => "A homoerotic volleyball montage.")
Answer.create!(:text => "A hot mess.")
Answer.create!(:text => "A Hungry-Man Frozen Christmas Dinner for One.")
Answer.create!(:text => "A lifetime of sadness.")
Answer.create!(:text => "A look-see.")
Answer.create!(:text => "A low standard of living.")
Answer.create!(:text => "A magic hippie love cloud.")
Answer.create!(:text => "A man in yoga pants with a ponytail and feather earrings.")
Answer.create!(:text => "A mating display.")
Answer.create!(:text => "A micropenis.")
Answer.create!(:text => "A middle-aged man on roller skates.")
Answer.create!(:text => "A mime having a stroke.")
Answer.create!(:text => "A monkey smoking a cigar.")
Answer.create!(:text => "A mopey zoo lion.")
Answer.create!(:text => "A murder most foul.")
Answer.create!(:text => "A nuanced critique.")
Answer.create!(:text => "A passionate Latino lover.")
Answer.create!(:text => "A pinata full of scorpions.")
Answer.create!(:text => "A really cool hat.")
Answer.create!(:text => "A rival dojo")
Answer.create!(:text => "A robust mongoloid.")
Answer.create!(:text => "A sad fat dragon with no friends.")
Answer.create!(:text => "A sad handjob.")
Answer.create!(:text => "A salty surprise.")
Answer.create!(:text => "A sassy black woman.")
Answer.create!(:text => "A sausage festival.")
Answer.create!(:text => "A sea of troubles.")
Answer.create!(:text => "A slightly shittier parallel universe.")
Answer.create!(:text => "A snapping turtle biting the tip of your penis.")
Answer.create!(:text => "A soulful rendition of “Ol' Man River.”")
Answer.create!(:text => "A squadron of moles wearing aviator goggles.")
Answer.create!(:text => "A stray pube.")
Answer.create!(:text => "A Super Soaker full of cat pee.")
Answer.create!(:text => "A sweaty, panting leather daddy.")
Answer.create!(:text => "A sweet spaceship.")
Answer.create!(:text => "A thermonuclear detonation.")
Answer.create!(:text => "A tiny horse.")
Answer.create!(:text => "A toxic family environment.")
Answer.create!(:text => "A visually arresting turtleneck.")
Answer.create!(:text => "A web of lies.")
Answer.create!(:text => "A windmill full of corpses.")
Answer.create!(:text => "A woman scorned.")
Answer.create!(:text => "A zesty breakfast burrito.")
Answer.create!(:text => "Aaron Burr.")
Answer.create!(:text => "Active listening.")
Answer.create!(:text => "Actually taking candy from a baby.")
Answer.create!(:text => "Adderall.")
Answer.create!(:text => "African children.")
Answer.create!(:text => "Agriculture.")
Answer.create!(:text => "AIDS.")
Answer.create!(:text => "Alcoholism.")
Answer.create!(:text => "All of this blood.")
Answer.create!(:text => "All-you-can-eat shrimp for $4.99.")
Answer.create!(:text => "Altar boys.")
Answer.create!(:text => "American Gladiators.")
Answer.create!(:text => "Amputees.")
Answer.create!(:text => "An army of skeletons.")
Answer.create!(:text => "An asymmetric boob job.")
Answer.create!(:text => "An erection that lasts more than four hours.")
Answer.create!(:text => "An ether-soaked rag.")
Answer.create!(:text => "An honest cop with nothing left to lose.")
Answer.create!(:text => "An icepick lobotomy.")
Answer.create!(:text => "An M. Night Shyamalan plot twist.")
Answer.create!(:text => "An Oedipus complex.")
Answer.create!(:text => "An unhinged ferris wheel rolling toward the sea.")
Answer.create!(:text => "Anal beads.")
Answer.create!(:text => "Another goddamn vampire movie.")
Answer.create!(:text => "Another shitty year.")
Answer.create!(:text => "Another shop of morphine.")
Answer.create!(:text => "Apologizing.")
Answer.create!(:text => "Appreciative snapping.")
Answer.create!(:text => "Arnold Schwarzenegger.")
Answer.create!(:text => "Asians who aren't good at math.")
Answer.create!(:text => "Assless chaps.")
Answer.create!(:text => "Attitude.")
Answer.create!(:text => "Auschwitz.")
Answer.create!(:text => "Authentic Mexican cuisine.")
Answer.create!(:text => "Autocannibalism.")
Answer.create!(:text => "AXE body spray.")
Answer.create!(:text => "Balls.")
Answer.create!(:text => "Barack Obama.")
Answer.create!(:text => "Basic human decency.")
Answer.create!(:text => "BATMAN!!!")
Answer.create!(:text => "Beating your wives.")
Answer.create!(:text => "Beefin' over turf.")
Answer.create!(:text => "Bees?")
Answer.create!(:text => "Being a bust adult with many important things to do.")
Answer.create!(:text => "Being a dick to children.")
Answer.create!(:text => "Being a dinosaur.")
Answer.create!(:text => "Being a motherfucking sorcerer.")
Answer.create!(:text => "Being awesome at sex.")
Answer.create!(:text => "Being fabulous.")
Answer.create!(:text => "Being marginalized.")
Answer.create!(:text => "Being on fire.")
Answer.create!(:text => "Being rich.")
Answer.create!(:text => "Bill Nye the Science Guy.")
Answer.create!(:text => "Bingeing and purging.")
Answer.create!(:text => "Bitches.")
Answer.create!(:text => "Black people.")
Answer.create!(:text => "Bling.")
Answer.create!(:text => "Booby-trapping the house to foil burglars.")
Answer.create!(:text => "Boogers.")
Answer.create!(:text => "Boris the Soviet Love Hammer.")
Answer.create!(:text => "Bosnian chicken farmers.")
Answer.create!(:text => "Breaking out into song and dance.")
Answer.create!(:text => "Britney Spears at 55.")
Answer.create!(:text => "Bullshit.")
Answer.create!(:text => "Cards Against Humanity.")
Answer.create!(:text => "Carnies.")
Answer.create!(:text => "Catapults.")
Answer.create!(:text => "Catastrophic Urethral Trauma.")
Answer.create!(:text => "Centaurs.")
Answer.create!(:text => "Chainsaws for hands.")
Answer.create!(:text => "Charisma.")
Answer.create!(:text => "Cheating in the Special Olympics.")
Answer.create!(:text => "Child abuse.")
Answer.create!(:text => "Child beauty pageants.")
Answer.create!(:text => "Children on leashes.")
Answer.create!(:text => "Chivalry.")
Answer.create!(:text => "Christopher Walken.")
Answer.create!(:text => "Civilian casualties.")
Answer.create!(:text => "Clams.")
Answer.create!(:text => "Classist Undertones.")
Answer.create!(:text => "Clearing a bloody path through Walmart with a scimitar.")
Answer.create!(:text => "Coat hanger abortions.")
Answer.create!(:text => "Cockfights.")
Answer.create!(:text => "College.")
Answer.create!(:text => "Concealing a boner.")
Answer.create!(:text => "Consultants.")
Answer.create!(:text => "Copping a feel.")
Answer.create!(:text => "Coughing into a vagina.")
Answer.create!(:text => "Count Chocula.")
Answer.create!(:text => "Crippling debt.")
Answer.create!(:text => "Crystal meth.")
Answer.create!(:text => "Cuddling.")
Answer.create!(:text => "Customer service representatives.")
Answer.create!(:text => "Cybernetic enhancements.")
Answer.create!(:text => "Daddy issues.")
Answer.create!(:text => "Daddy's belt.")
Answer.create!(:text => "Dancing with a broom.")
Answer.create!(:text => "Darth Vader.")
Answer.create!(:text => "Date rape.")
Answer.create!(:text => "Dead babies.")
Answer.create!(:text => "Dead parents.")
Answer.create!(:text => "Death by Steven Seagal.")
Answer.create!(:text => "Deflowering the princess.")
Answer.create!(:text => "Dental dams.")
Answer.create!(:text => "Dick Cheney.")
Answer.create!(:text => "Dick fingers.")
Answer.create!(:text => "Dining with cardboard cutouts of the cast of “Friends.”")
Answer.create!(:text => "Doin' it in the butt.")
Answer.create!(:text => "Doing the right thing.")
Answer.create!(:text => "Domino's Oreo Dessert Pizza.")
Answer.create!(:text => "Dorito breath.")
Answer.create!(:text => "Double penetration.")
Answer.create!(:text => "Drinking alone.")
Answer.create!(:text => "Dropping a chandelier on your enemies and riding the rope up.")
Answer.create!(:text => "Dry heaving.")
Answer.create!(:text => "Dwarf tossing.")
Answer.create!(:text => "Dying of dysentery.")
Answer.create!(:text => "Dying.")
Answer.create!(:text => "Eating all of the cookies before the AIDS bake-sale.")
Answer.create!(:text => "Eating an albino.")
Answer.create!(:text => "Eating an entire snowman.")
Answer.create!(:text => "Eating the last known Bison.")
Answer.create!(:text => "Edible underpants.")
Answer.create!(:text => "Elderly Japanese men.")
Answer.create!(:text => "Elf cum.")
Answer.create!(:text => "Embryonic stem cells.")
Answer.create!(:text => "Emotions.")
Answer.create!(:text => "Enormous Scandinavian women.")
Answer.create!(:text => "Erectile dysfunction.")
Answer.create!(:text => "Estrogen.")
Answer.create!(:text => "Ethnic cleansing.")
Answer.create!(:text => "Eugenics.")
Answer.create!(:text => "Euphoria by Calvin Klein.")
Answer.create!(:text => "Exactly what you'd expect.")
Answer.create!(:text => "Exchanging pleasantries.")
Answer.create!(:text => "Existing.")
Answer.create!(:text => "Expecting a burp and vomiting on the floor.")
Answer.create!(:text => "Explosions.")
Answer.create!(:text => "Fabricating statistics.")
Answer.create!(:text => "Famine.")
Answer.create!(:text => "Fancy Feast.")
Answer.create!(:text => "Farting and walking away.")
Answer.create!(:text => "Fear itself.")
Answer.create!(:text => "Feeding Rosie O'Donnell.")
Answer.create!(:text => "Fetal alcohol syndrome.")
Answer.create!(:text => "Fiery poops.")
Answer.create!(:text => "Figgy pudding.")
Answer.create!(:text => "Finding a skeleton.")
Answer.create!(:text => "Finding Waldo.")
Answer.create!(:text => "Finger painting.")
Answer.create!(:text => "Fingering.")
Answer.create!(:text => "Firing a rifle into the air while balls deep in a squealing hog.")
Answer.create!(:text => "Five-Dollar Footlongs.")
Answer.create!(:text => "Flash flooding.")
Answer.create!(:text => "Flesh-eating bacteria.")
Answer.create!(:text => "Flightless birds.")
Answer.create!(:text => "Flying sex snakes.")
Answer.create!(:text => "Foreskin.")
Answer.create!(:text => "Forgetting the Alamo.")
Answer.create!(:text => "Former President George W. Bush.")
Answer.create!(:text => "Free samples.")
Answer.create!(:text => "Friction.")
Answer.create!(:text => "Friendly fire.")
Answer.create!(:text => "Friends who eat all the snacks.")
Answer.create!(:text => "Friends with benefits.")
Answer.create!(:text => "Frolicking.")
Answer.create!(:text => "Fuck Mountain.")
Answer.create!(:text => "Fucking up “Silent Night” in front of 300 parents.")
Answer.create!(:text => "Full frontal nudity.")
Answer.create!(:text => "Gandalf.")
Answer.create!(:text => "Geese.")
Answer.create!(:text => "Genetically engineered super-soldiers.")
Answer.create!(:text => "Genghis Khan.")
Answer.create!(:text => "Genital piercings.")
Answer.create!(:text => "George Clooney's musk.")
Answer.create!(:text => "German dungeon porn.")
Answer.create!(:text => "Getting abducted by Peter Pan.")
Answer.create!(:text => "Getting drunk on mouthwash.")
Answer.create!(:text => "Getting hilariously gang-banged by the Blue Man Group.")
Answer.create!(:text => "Getting in her pants, politely.")
Answer.create!(:text => "Getting naked and watching Nickelodeon.")
Answer.create!(:text => "Getting really high.")
Answer.create!(:text => "Getting so angry that you pop a boner.")
Answer.create!(:text => "Ghandi.")
Answer.create!(:text => "Ghosts.")
Answer.create!(:text => "Gift-wrapping a live hamster.")
Answer.create!(:text => "Giving 110%.")
Answer.create!(:text => "Gladitorial combat.")
Answer.create!(:text => "Glenn Beck being harried by a swarm of buzzards.")
Answer.create!(:text => "Glenn Beck catching his scrotum on a curtain hook.")
Answer.create!(:text => "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.")
Answer.create!(:text => "Global warming.")
Answer.create!(:text => "Gloryholes.")
Answer.create!(:text => "Goats eating cans.")
Answer.create!(:text => "Goblins.")
Answer.create!(:text => "God.")
Answer.create!(:text => "GoGurt.")
Answer.create!(:text => "Golden showers.")
Answer.create!(:text => "Good grammar.")
Answer.create!(:text => "Grandma.")
Answer.create!(:text => "Grandpa's ashes.")
Answer.create!(:text => "Graphic violence, adult language and some sexual content.")
Answer.create!(:text => "Grave robbing.")
Answer.create!(:text => "Guys who don't call.")
Answer.create!(:text => "Half-assed foreplay.")
Answer.create!(:text => "Harry Potter erotica.")
Answer.create!(:text => "Heartwarming orphans.")
Answer.create!(:text => "Her Royal Highness, Queen Elizabeth II.")
Answer.create!(:text => "Heteronormativity.")
Answer.create!(:text => "Hillary Clinton's death stare.")
Answer.create!(:text => "Hipsters.")
Answer.create!(:text => "Historical revisionism.")
Answer.create!(:text => "Historically black colleges.")
Answer.create!(:text => "Home video of Oprah sobbing into a Lean Cuisine.")
Answer.create!(:text => "Homeless people.")
Answer.create!(:text => "Hope.")
Answer.create!(:text => "Hormone injections.")
Answer.create!(:text => "Horrifying laser hair removal accidents.")
Answer.create!(:text => "Horse meat.")
Answer.create!(:text => "Hot Cheese.")
Answer.create!(:text => "Hot people.")
Answer.create!(:text => "Hot Pockets.")
Answer.create!(:text => "Hulk Hogan.")
Answer.create!(:text => "Hurricane Katrina.")
Answer.create!(:text => "Immaculate conception.")
Answer.create!(:text => "Inappropriate yodeling.")
Answer.create!(:text => "Incest.")
Answer.create!(:text => "Insatiable bloodlust.")
Answer.create!(:text => "Intelligent design.")
Answer.create!(:text => "Intimacy problems.")
Answer.create!(:text => "Italians.")
Answer.create!(:text => "Jafar.")
Answer.create!(:text => "Jean-Claude Van Damme.")
Answer.create!(:text => "Jeff Goldblum.")
Answer.create!(:text => "Jerking off into a pool of children's tears.")
Answer.create!(:text => "Jew-fros.")
Answer.create!(:text => "Jewish fraternities.")
Answer.create!(:text => "Jibber-jabber.")
Answer.create!(:text => "John Wilkes Booth.")
Answer.create!(:text => "Judge Judy.")
Answer.create!(:text => "Just the tip.")
Answer.create!(:text => "Justin Bieber.")
Answer.create!(:text => "Kamikaze pilots.")
Answer.create!(:text => "Kanye West.")
Answer.create!(:text => "Keanu Reaves.")
Answer.create!(:text => "Keg stands.")
Answer.create!(:text => "Kids with ass cancer.")
Answer.create!(:text => "Kim-Jong-il.")
Answer.create!(:text => "Krampus, the Austrian Christmas Monster.")
Answer.create!(:text => "Lactation.")
Answer.create!(:text => "Lady Gaga.")
Answer.create!(:text => "Lance Armstrong's missing testicle.")
Answer.create!(:text => "Land mines.")
Answer.create!(:text => "Laying an egg.")
Answer.create!(:text => "Leaving an awkward voicemail.")
Answer.create!(:text => "Leprosy.")
Answer.create!(:text => "Leveling up.")
Answer.create!(:text => "Licking things to claim them as your own.")
Answer.create!(:text => "Literally eating shit.")
Answer.create!(:text => "Living in a trashcan.")
Answer.create!(:text => "Lockjaw.")
Answer.create!(:text => "Loki, the trickster god.")
Answer.create!(:text => "Loose lips.")
Answer.create!(:text => "Lumberjack fantasies.")
Answer.create!(:text => "Lunchables.")
Answer.create!(:text => "Mad hacky-sack skills.")
Answer.create!(:text => "Making a friend.")
Answer.create!(:text => "Making a pouty face.")
Answer.create!(:text => "Making the penises kiss.")
Answer.create!(:text => "Making the penises kiss.")
Answer.create!(:text => "Mall Santa.")
Answer.create!(:text => "Man meat.")
Answer.create!(:text => "Masturbation.")
Answer.create!(:text => "Me time.")
Answer.create!(:text => "Me.")
Answer.create!(:text => "MechaHitler.")
Answer.create!(:text => "Media coverage.")
Answer.create!(:text => "Medieval Times Dinner & Tournament.")
Answer.create!(:text => "Men.")
Answer.create!(:text => "Menstruation.")
Answer.create!(:text => "Michael Jackson.")
Answer.create!(:text => "Michelle Obama's arms.")
Answer.create!(:text => "Mild autism.")
Answer.create!(:text => "Mooing.")
Answer.create!(:text => "Moral ambiguity.")
Answer.create!(:text => "Morgan Freeman's voice.")
Answer.create!(:text => "Mouth herpes.")
Answer.create!(:text => "Mr. Clean, right behind you.")
Answer.create!(:text => "Muhammad (Praise Be Unto Him).")
Answer.create!(:text => "Multiple stab wounds.")
Answer.create!(:text => "Mutually-assured destruction.")
Answer.create!(:text => "My collection of high-tech sex toys.")
Answer.create!(:text => "My first kill.")
Answer.create!(:text => "My genitals.")
Answer.create!(:text => "My hot cousin.")
Answer.create!(:text => "My humps.")
Answer.create!(:text => "My inner demons.")
Answer.create!(:text => "My machete.")
Answer.create!(:text => "My relationship status.")
Answer.create!(:text => "My sex life.")
Answer.create!(:text => "My soul.")
Answer.create!(:text => "My vagina.")
Answer.create!(:text => "Natalie Portman.")
Answer.create!(:text => "Natural male enhancement.")
Answer.create!(:text => "Natural selection.")
Answer.create!(:text => "Nazis.")
Answer.create!(:text => "Necrophilia.")
Answer.create!(:text => "Neil Patrick Harris.")
Answer.create!(:text => "New Age music.")
Answer.create!(:text => "Nickelback.")
Answer.create!(:text => "Nicolas Cage.")
Answer.create!(:text => "Nipple blades.")
Answer.create!(:text => "Nocturnal emissions.")
Answer.create!(:text => "Not giving a shit about the Third World.")
Answer.create!(:text => "Not reciprocating oral sex.")
Answer.create!(:text => "Nublile slave boys.")
Answer.create!(:text => "Nunchuck moves.")
Answer.create!(:text => "Obesity.")
Answer.create!(:text => "Object permanence.")
Answer.create!(:text => "Old-people smell.")
Answer.create!(:text => "Ominous background music.")
Answer.create!(:text => "One Ring to rule them all.")
Answer.create!(:text => "One thousand Slim Jims.")
Answer.create!(:text => "Oompa-Loompas.")
Answer.create!(:text => "Opposable thumbs.")
Answer.create!(:text => "Overcompensation.")
Answer.create!(:text => "Overpowering your father.")
Answer.create!(:text => "Oversized lollipops.")
Answer.create!(:text => "Pabst Blue Ribbon.")
Answer.create!(:text => "Pac-Man uncontrollably guzzling cum.")
Answer.create!(:text => "Panda sex.")
Answer.create!(:text => "Panty raids.")
Answer.create!(:text => "Parting the Red Sea.")
Answer.create!(:text => "Party poopers.")
Answer.create!(:text => "Passable transvestites.")
Answer.create!(:text => "Passing a kidney stone.")
Answer.create!(:text => "Passive-aggressive Post-it notes.")
Answer.create!(:text => "Pedophiles.")
Answer.create!(:text => "Peeing a little bit.")
Answer.create!(:text => "Penis envy.")
Answer.create!(:text => "Picking up girls at the abortion clinic.")
Answer.create!(:text => "Pictures of boobs.")
Answer.create!(:text => "Pistol-whipping a hostage.")
Answer.create!(:text => "Pixelated bukkake.")
Answer.create!(:text => "Police brutality.")
Answer.create!(:text => "Pooping back and forth. Forever.")
Answer.create!(:text => "Poor life choices.")
Answer.create!(:text => "Poor people.")
Answer.create!(:text => "Poorly-timed Holocaust jokes.")
Answer.create!(:text => "Porn stars.")
Answer.create!(:text => "Powerful thighs.")
Answer.create!(:text => "Prancing.")
Answer.create!(:text => "Praying the gay away.")
Answer.create!(:text => "Preteens.")
Answer.create!(:text => "Pretending to be happy.")
Answer.create!(:text => "Pretending to care.")
Answer.create!(:text => "Pretty Pretty Princess Dress-Up Board Game.")
Answer.create!(:text => "Pterodactyl eggs.")
Answer.create!(:text => "Puberty.")
Answer.create!(:text => "Public ridicule.")
Answer.create!(:text => "Pulling out,")
Answer.create!(:text => "Pumping out a baby every nine months.")
Answer.create!(:text => "Puppies!")
Answer.create!(:text => "Queefing.")
Answer.create!(:text => "Quiche.")
Answer.create!(:text => "Quivering jowls.")
Answer.create!(:text => "Racially-biased SAT questions.")
Answer.create!(:text => "Racism.")
Answer.create!(:text => "Raping and pillaging.")
Answer.create!(:text => "Re-gifting.")
Answer.create!(:text => "Repression,.")
Answer.create!(:text => "Republicans.")
Answer.create!(:text => "Revenge fucking.")
Answer.create!(:text => "Riding off into the sunset.")
Answer.create!(:text => "Ripping into a man's chest and pulling out his still-beating heart.")
Answer.create!(:text => "Rising from the grave.")
Answer.create!(:text => "Road head.")
Answer.create!(:text => "Robert Downey, Jr.")
Answer.create!(:text => "RoboCop.")
Answer.create!(:text => "Ronald Reagan.")
Answer.create!(:text => "Roofies.")
Answer.create!(:text => "Ryan Gosling riding in on a white horse.")
Answer.create!(:text => "Same-sex ice dancing.")
Answer.create!(:text => "Santa Claus.")
Answer.create!(:text => "Santa's heavy sack.")
Answer.create!(:text => "Sarah Palin.")
Answer.create!(:text => "Saxophone solos.")
Answer.create!(:text => "Scalping.")
Answer.create!(:text => "Science.")
Answer.create!(:text => "Scientology,")
Answer.create!(:text => "Scrotal frostbite.")
Answer.create!(:text => "Scrotum tickling.")
Answer.create!(:text => "Scrubbing under the folds.")
Answer.create!(:text => "Sean Connery.")
Answer.create!(:text => "Sean Penn.")
Answer.create!(:text => "Seduction.")
Answer.create!(:text => "Self-loathing.")
Answer.create!(:text => "Seppuku.")
Answer.create!(:text => "Serfdom.")
Answer.create!(:text => "Several intertwining love stories featuring Hugh Grant.")
Answer.create!(:text => "Sexting.")
Answer.create!(:text => "Sexual humiliation.")
Answer.create!(:text => "Sexual tension.")
Answer.create!(:text => "Sexy pillow fights.")
Answer.create!(:text => "Sexy siamese twins.")
Answer.create!(:text => "Shaft.")
Answer.create!(:text => "Shapeshifters.")
Answer.create!(:text => "Shaquille O'Neal's acting career.")
Answer.create!(:text => "Sharing needles.")
Answer.create!(:text => "Skeletor.")
Answer.create!(:text => "Slow motion.")
Answer.create!(:text => "Smallpox blankets.")
Answer.create!(:text => "Smegma.")
Answer.create!(:text => "Sniffing glue.")
Answer.create!(:text => "Socks.")
Answer.create!(:text => "Soiling oneself.")
Answer.create!(:text => "Some really fucked-up shit.")
Answer.create!(:text => "Soup that is too hot.")
Answer.create!(:text => "Space Jam on VHS.")
Answer.create!(:text => "Space muffins.")
Answer.create!(:text => "Special musical guest, Cher.")
Answer.create!(:text => "Spectacular abs.")
Answer.create!(:text => "Sperm whales.")
Answer.create!(:text => "Spontaneous human combustion.")
Answer.create!(:text => "Spring break!")
Answer.create!(:text => "Statistically validated stereotypes.")
Answer.create!(:text => "Stephen Hawking talking dirty.")
Answer.create!(:text => "Stifling a giggle at the mention of Hutus and Tutsis.")
Answer.create!(:text => "Stranger danger.")
Answer.create!(:text => "Subduing a grizzly bear and making her your wife.")
Answer.create!(:text => "Sudden Poop Explosion Disease.")
Answer.create!(:text => "Suicidal thoughts.")
Answer.create!(:text => "Sunshine and rainbows.")
Answer.create!(:text => "Surprise sex!")
Answer.create!(:text => "Survivor's guilt.")
Answer.create!(:text => "Sweet, sweet vengeance.")
Answer.create!(:text => "Swiftly achieving orgasm.")
Answer.create!(:text => "Switching to Geico.")
Answer.create!(:text => "Swooping.")
Answer.create!(:text => "Take-backsies.")
Answer.create!(:text => "Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.")
Answer.create!(:text => "Taking down Santa with a surface-to-air missiles.")
Answer.create!(:text => "Taking off your shirt.")
Answer.create!(:text => "Tangled Slinkys.")
Answer.create!(:text => "Tasteful sideboob.")
Answer.create!(:text => "Teaching a robot to love.")
Answer.create!(:text => "Team-building exercises.")
Answer.create!(:text => "Teenage pregnancy.")
Answer.create!(:text => "Tentacle porn.")
Answer.create!(:text => "Testicular torsion.")
Answer.create!(:text => "That thing that electrocutes your abs.")
Answer.create!(:text => "The American Dream.")
Answer.create!(:text => "The Big Bang.")
Answer.create!(:text => "The Blood of Christ.")
Answer.create!(:text => "The boners of the elderly.")
Answer.create!(:text => "The Care Bear Stare.")
Answer.create!(:text => "The Chinese gymnastics team.")
Answer.create!(:text => "The chronic.")
Answer.create!(:text => "The clitoris.")
Answer.create!(:text => "The corporations.")
Answer.create!(:text => "The Dance of the Sugar Plum Fairy.")
Answer.create!(:text => "The day the birds attacked.")
Answer.create!(:text => "The Donald Trump Seal of Approval.")
Answer.create!(:text => "The economy.")
Answer.create!(:text => "The Fanta girls.")
Answer.create!(:text => "The folly of man.")
Answer.create!(:text => "The forbidden fruit.")
Answer.create!(:text => "The Force.")
Answer.create!(:text => "The four arms of Vishnu.")
Answer.create!(:text => "The gays.")
Answer.create!(:text => "The glass ceiling.")
Answer.create!(:text => "The Google.")
Answer.create!(:text => "The grey nutrient broth that sustains Mitt Romney.")
Answer.create!(:text => "The Gulags.")
Answer.create!(:text => "The Hamburglar.")
Answer.create!(:text => "The hardworking Mexican.")
Answer.create!(:text => "The harsh light of day.")
Answer.create!(:text => "The heart of a child.")
Answer.create!(:text => "The hiccups.")
Answer.create!(:text => "The Holy Bible.")
Answer.create!(:text => "The homosexual agenda.")
Answer.create!(:text => "The human body.")
Answer.create!(:text => "The Hustle.")
Answer.create!(:text => "The inevitable heat death of the universe.")
Answer.create!(:text => "The invisible hand.")
Answer.create!(:text => "The Jews.")
Answer.create!(:text => "The KKK.")
Answer.create!(:text => "The Kool-Aid Man.")
Answer.create!(:text => "The Little Engine That Could.")
Answer.create!(:text => "The Make-A-Wish foundation.")
Answer.create!(:text => "The mere concept of Applebee's.")
Answer.create!(:text => "The milk man.")
Answer.create!(:text => "The miracle of childbirth.")
Answer.create!(:text => "The mixing of the races.")
Answer.create!(:text => "The new Radiohead album.")
Answer.create!(:text => "The placenta.")
Answer.create!(:text => "The Pope.")
Answer.create!(:text => "The profoundly handicapped.")
Answer.create!(:text => "The Rapture.")
Answer.create!(:text => "The Rev. Dr. Martin Luther King, Jr.")
Answer.create!(:text => "The shambling corpse of Larry King.")
Answer.create!(:text => "The South.")
Answer.create!(:text => "The Star Wars Holiday Special.")
Answer.create!(:text => "The taint; the grundle; the fleshy fun-bridge.")
Answer.create!(:text => "The Tempur-Pedic Swedish Sleep System.")
Answer.create!(:text => "The terrorists.")
Answer.create!(:text => "The Three-Fifths Compromise.")
Answer.create!(:text => "The tiny calloused hands of the Chinese  children that made this card.")
Answer.create!(:text => "The token minority.")
Answer.create!(:text => "The Trail of Tears.")
Answer.create!(:text => "The true meaning of Christmas.")
Answer.create!(:text => "The Ubermensch.")
Answer.create!(:text => "The underground railroad.")
Answer.create!(:text => "The violation of our most basic human rights.")
Answer.create!(:text => "The Virginia Tech Massacre.")
Answer.create!(:text => "The World of Warcraft.")
Answer.create!(:text => "Third base.")
Answer.create!(:text => "Tiny nipples.")
Answer.create!(:text => "Tom Cruise.")
Answer.create!(:text => "Tongue.")
Answer.create!(:text => "Toni Morrison's vagina.")
Answer.create!(:text => "Too much hair gel.")
Answer.create!(:text => "Tripping balls.")
Answer.create!(:text => "Two midgets shitting into a bucket.")
Answer.create!(:text => "Unfathomable stupidity.")
Answer.create!(:text => "Upgrading homeless people to mobile hotspots.")
Answer.create!(:text => "Uppercuts.")
Answer.create!(:text => "Vehicular manslaughter.")
Answer.create!(:text => "Viagra.")
Answer.create!(:text => "Vigilante justice.")
Answer.create!(:text => "Vigorous jazz hands.")
Answer.create!(:text => "Vikings.")
Answer.create!(:text => "Waiting 'til marriage.")
Answer.create!(:text => "Waking up half-naked in a Denny's parking lot.")
Answer.create!(:text => "Waterboarding.")
Answer.create!(:text => "Weapons-grade plutonium.")
Answer.create!(:text => "Wearing an octopus for a hat.")
Answer.create!(:text => "Wearing underwear inside-out to avoid doing laundry.")
Answer.create!(:text => "Whatever Kwanzaa is supposed to be about.")
Answer.create!(:text => "When you fart and a little bit comes out.")
Answer.create!(:text => "Whining like a little bitch.")
Answer.create!(:text => "Whipping a disobedient slave.")
Answer.create!(:text => "Whipping it out.")
Answer.create!(:text => "White people.")
Answer.create!(:text => "White privilege.")
Answer.create!(:text => "Wifely duties.")
Answer.create!(:text => "William Shatner.")
Answer.create!(:text => "Winking at old people.")
Answer.create!(:text => "Wiping her butt.")
Answer.create!(:text => "Women in yogurt commercials.")
Answer.create!(:text => "Women's suffrage.")
Answer.create!(:text => "Words, words, words.")
Answer.create!(:text => "World peace.")
Answer.create!(:text => "Yeast.")
Answer.create!(:text => "YOU MUST CONSTRUCT ADDITIONAL PYLONS.")
Answer.create!(:text => "Zeus's sexual appetites.")

Question.create!(:text => "________, kid-tested mother-approved.", :blanks => 1)
Question.create!(:text => "________: good to the last drop.", :blanks => 1)
Question.create!(:text => "________? There's an app for that.", :blanks => 1)
Question.create!(:text => "________. Betcha can't have just one.", :blanks => 1)
Question.create!(:text => "________. High five bro.", :blanks => 1)
Question.create!(:text => "________. It's a trap!", :blanks => 1)
Question.create!(:text => "________. That's how I want to die.", :blanks => 1)
Question.create!(:text => "________ + ________ = ________", :blanks => 3)
Question.create!(:text => "I went from ________ to ________, all thanks to ________.", :blanks => 3)
Question.create!(:text => "Make a haiku. ________ ________ ________", :blanks => 3)
Question.create!(:text => "________ would be woefully incomplete without ________.", :blanks => 2)
Question.create!(:text => "________ is a slippery slope that leads to ________.", :blanks => 2)
Question.create!(:text => "An international tribunal has found ________ guilty of ________.", :blanks => 2)
Question.create!(:text => "An the Academy Award for ________ goes to ________.", :blanks => 2)
Question.create!(:text => "Before ________, all we had was ________.", :blanks => 2)
Question.create!(:text => "Dear Sir or Madam, We regret to inform you that the office of ________ has denied your request for ________.", :blanks => 2)
Question.create!(:text => "For my next trick, I will pull ________ out of ________.", :blanks => 2)
Question.create!(:text => "I never truly understood ________ until I encountered ________.", :blanks => 2)
Question.create!(:text => "I spent my whole life working toward ________, only to have it ruined by ________.", :blanks => 2)
Question.create!(:text => "If God didn't want us to enjoy ________, he wouldn't have given us ________.", :blanks => 2)
Question.create!(:text => "In a pinch, ________ can be a suitable substitute for ________.", :blanks => 2)
Question.create!(:text => "In a world ravaged by ________, our only solace is ________.", :blanks => 2)
Question.create!(:text => "In M. Night Shamalan's new movie, Bruce Willis discovers that ________ had really been ________ all along.", :blanks => 2)
Question.create!(:text => "Lifetime presents ________, the story of ________.", :blanks => 2)
Question.create!(:text => "Michael Bay's new three-hour action epic pits ________ against ________.", :blanks => 2)
Question.create!(:text => "Rumor has it that Vladimir Putin's favorite dish is ________ stuffed with ________.", :blanks => 2)
Question.create!(:text => "Step 1: ________ Step 2 ________ Step 3: Profit.", :blanks => 2)
Question.create!(:text => "That's right I killed ________. How you ask? ________.", :blanks => 2)
Question.create!(:text => "What's the next superhero/sidekick duo? ________ and ________", :blanks => 2)
Question.create!(:text => "When I was tripping on acid ________ turned into ________.", :blanks => 2)
Question.create!(:text => "You haven't truly lived until you've experienced ________ and ________ at the same time.", :blanks => 2)
Question.create!(:text => "A romantic candlelit dinner would be incomplete without ________.", :blanks => 1)
Question.create!(:text => "After blacking out during New Year's Eve, I was awoken by ________.", :blanks => 1)
Question.create!(:text => "After months of debate, the Occupy Wall Street General Assembly could only agree on “More ________!”", :blanks => 1)
Question.create!(:text => "After the earthquake, Sean Penn bought ________ to the people of Haiti.", :blanks => 1)
Question.create!(:text => "Alternative medicine is now embracing the curative powers of ________.", :blanks => 1)
Question.create!(:text => "And I would have gotten away with it, too, if it hadn't been for ________.", :blanks => 1)
Question.create!(:text => "Anthropologists have recently discovered a primitive tribe that worships ________.", :blanks => 1)
Question.create!(:text => "Before I run for president, I must destroy all evidence of my involvement with ________.", :blanks => 1)
Question.create!(:text => "BILLY MAYS HERE FOR ________.", :blanks => 1)
Question.create!(:text => "But before I kill you, Mr. Bond, I must show you ________.", :blanks => 1)
Question.create!(:text => "Charades was ruined for me forever when my mom had to act out ________.", :blanks => 1)
Question.create!(:text => "Coming to Broadway this season, ________: The Musical.", :blanks => 1)
Question.create!(:text => "Dear Abby, I'm having some trouble with ________ and would like your advice.", :blanks => 1)
Question.create!(:text => "During his midlife crisis, my dad got really into ________.", :blanks => 1)
Question.create!(:text => "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ________.", :blanks => 1)
Question.create!(:text => "During sex, I like to think about ________.", :blanks => 1)
Question.create!(:text => "Every Christmas my uncle gets drunk and tells the story about ________.", :blanks => 1)
Question.create!(:text => "Everyone down on the ground! We don't want to hurt anyone. We're just here for ________.", :blanks => 1)
Question.create!(:text => "He who controls ________ controls the world.", :blanks => 1)
Question.create!(:text => "How am I maintaining my relationship status? ________", :blanks => 1)
Question.create!(:text => "I do not know with what weapons World War III will be fought, but World War IV will be fought with ________.", :blanks => 1)
Question.create!(:text => "I drink to forget ________.", :blanks => 1)
Question.create!(:text => "I got 99 problems but ________ ain't one.", :blanks => 1)
Question.create!(:text => "I learned the hard way that you can't cheer up a grieving friend with ________.", :blanks => 1)
Question.create!(:text => "I'm sorry professor, but I couldn't complete my homework because of ________.", :blanks => 1)
Question.create!(:text => "In 1,000 years when paper money is but a distant memory, ________ will be our currency.", :blanks => 1)
Question.create!(:text => "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ________.", :blanks => 1)
Question.create!(:text => "In his new self-produced album, Kanye West raps over the sounds of ________.", :blanks => 1)
Question.create!(:text => "In his newest and most difficult stunt, David Blaine must escape from ________.", :blanks => 1)
Question.create!(:text => "In its new tourism campaign, Detroit proclaims that it has finally eliminated ________.", :blanks => 1)
Question.create!(:text => "In L.A. county Jail, word is you can trade 200 cigarettes for ________.", :blanks => 1)
Question.create!(:text => "In Michael Jackson's final moments, he thought about ________.", :blanks => 1)
Question.create!(:text => "In Rome, there are whisperings that the Vatican has a secret room devoted to ________.", :blanks => 1)
Question.create!(:text => "In the distant future, historians will agree that ________ marked the beginning of America's decline.", :blanks => 1)
Question.create!(:text => "In the new Disney Channel Original Movie, Hannah Montana struggles with ________ for the first time.", :blanks => 1)
Question.create!(:text => "Instead of coal, Santa now gives the bad children ________ .", :blanks => 1)
Question.create!(:text => "It's a pity that kids these days are all getting involved with ________.", :blanks => 1)
Question.create!(:text => "Jesus is ________.", :blanks => 1)
Question.create!(:text => "Life for American Indians was forever changed when the White Man introduced them to ________.", :blanks => 1)
Question.create!(:text => "Little Miss Muffet, Sat on a tuffet, Eating her curds and ________.", :blanks => 1)
Question.create!(:text => "Major League Baseball has banned ________ for giving players an unfair advantage.", :blanks => 1)
Question.create!(:text => "Maybe she's born with it. Maybe it's ________.", :blanks => 1)
Question.create!(:text => "Members of New York's social elite are paying thousands of dollars just to experience ________.", :blanks => 1)
Question.create!(:text => "MTV's new reality show features eight washed-up celebrities living with ________.", :blanks => 1)
Question.create!(:text => "My country, 'tis of thee, sweet land of ________.", :blanks => 1)
Question.create!(:text => "My mom freaked out when she looked at my browser history and found ________.com/________.", :blanks => 2)
Question.create!(:text => "My new favorite porn star is Joey “________” McGee.", :blanks => 1)
Question.create!(:text => "Next from J.K. Rowling: Harry Potter and the Chamber of ________.", :blanks => 1)
Question.create!(:text => "Next on ESPN2: The World Series of ________.", :blanks => 1)
Question.create!(:text => "Next time on Dr. Phil: How to talk to your child about ________.", :blanks => 1)
Question.create!(:text => "On the third day of Christmas, my true love game to me: three French hens, two turtle doves, and ________.", :blanks => 1)
Question.create!(:text => "Only two things in life are certain: death and ________.", :blanks => 1)
Question.create!(:text => "Science will never explain the origin of ________.", :blanks => 1)
Question.create!(:text => "Studies show that lab rats navigate mazes 50% faster after being exposed to ________", :blanks => 1)
Question.create!(:text => "The CIA now interrogates enemy agents by repeatedly subjecting them to ________.", :blanks => 1)
Question.create!(:text => "The class field trip was completely ruined by ________.", :blanks => 1)
Question.create!(:text => "The Five Stages of Grief: denial, anger, bargaining, ________ acceptance.", :blanks => 1)
Question.create!(:text => "The healing process began when I joined a support group for victims of ________.", :blanks => 1)
Question.create!(:text => "The socialist governments of Scandanavia have declared that access to ________ is a basic human right.", :blanks => 1)
Question.create!(:text => "The votes are in, and the new high school mascot is ________.", :blanks => 1)
Question.create!(:text => "This holiday season, Tim Allen must overcome his fear of ________ to save Christmas.", :blanks => 1)
Question.create!(:text => "This is the way the world ends This is the way the world ends Not with a bang but with ________.", :blanks => 1)
Question.create!(:text => "This is your captain speaking. Fasten your seatbelts and prepare for ________.", :blanks => 1)
Question.create!(:text => "This month's Cosmo: “Spice up your sex life by bringing ________ into the bedroom.”", :blanks => 1)
Question.create!(:text => "This reason on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only ________ and his wits.", :blanks => 1)
Question.create!(:text => "Tonight on 20/20: What you don't know about ________ could kill you.", :blanks => 1)
Question.create!(:text => "TSA guidelines now prohibit ________ on airplanes.", :blanks => 1)
Question.create!(:text => "Wake up, America. Christmas is under attack by secular liberals and their ________.", :blanks => 1)
Question.create!(:text => "War! What is it good for? ________", :blanks => 1)
Question.create!(:text => "What am I giving up for Lent? ________", :blanks => 1)
Question.create!(:text => "What are my parents hiding from me? ________", :blanks => 1)
Question.create!(:text => "What brought the orgy to a grinding halt? ________", :blanks => 1)
Question.create!(:text => "What did I bring back from Mexico? ________", :blanks => 1)
Question.create!(:text => "What did the US airdrop to the children of Afghanistan? ________", :blanks => 1)
Question.create!(:text => "What did Vin Diesel eat for dinner? ________", :blanks => 1)
Question.create!(:text => "What do old people smell like? ________", :blanks => 1)
Question.create!(:text => "What does Dick Cheney prefer? ________", :blanks => 1)
Question.create!(:text => "What don't you want to find in your Chinese food? ________", :blanks => 1)
Question.create!(:text => "What ended my last relationship? ________", :blanks => 1)
Question.create!(:text => "What gets better with age? ________", :blanks => 1)
Question.create!(:text => "What gives me uncontrollable gas? ________", :blanks => 1)
Question.create!(:text => "What has been making life difficult at the nudist colony? ________", :blanks => 1)
Question.create!(:text => "What helps Obama unwind? ________", :blanks => 1)
Question.create!(:text => "What is Batman's guilty pleasure? ________", :blanks => 1)
Question.create!(:text => "What keeps me warm during the cold, cold winter? ________", :blanks => 1)
Question.create!(:text => "What never fails to liven up the party? ________", :blanks => 1)
Question.create!(:text => "What people like ________.", :blanks => 1)
Question.create!(:text => "What will always get you laid? ________", :blanks => 1)
Question.create!(:text => "What will I bring back in time to convince people that I am a powerful wizard? ________", :blanks => 1)
Question.create!(:text => "What would grandma find disturbing, yet oddly charming? ________", :blanks => 1)
Question.create!(:text => "What's a girl's best friend? ________", :blanks => 1)
Question.create!(:text => "What's my anti-drug? ________", :blanks => 1)
Question.create!(:text => "What's my secret power? ________", :blanks => 1)
Question.create!(:text => "What's Teach for America using to inspire inner city students to succeed? ________", :blanks => 1)
Question.create!(:text => "What's that smell? ________", :blanks => 1)
Question.create!(:text => "What's that sound? ________", :blanks => 1)
Question.create!(:text => "What's the crustiest? ________", :blanks => 1)
Question.create!(:text => "What's the gift that keeps on giving? ________", :blanks => 1)
Question.create!(:text => "What's the most emo? ________", :blanks => 1)
Question.create!(:text => "What's the new fad diet? ________", :blanks => 1)
Question.create!(:text => "What's the next Happy Meal toy? ________", :blanks => 1)
Question.create!(:text => "What's there a ton of in heaven? ________", :blanks => 1)
Question.create!(:text => "When all else fails, I can always masturbate to ________.", :blanks => 1)
Question.create!(:text => "When I am a billionaire, I shall erect a 50-foot statue to commemorate ________.", :blanks => 1)
Question.create!(:text => "When I am President of the United States, I will create the Department of ________.", :blanks => 1)
Question.create!(:text => "When I pooped, what came out of my butt? ________", :blanks => 1)
Question.create!(:text => "When Pharaoh remained unmoved, Moses called down a Plague of ________.", :blanks => 1)
Question.create!(:text => "When the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ________.", :blanks => 1)
Question.create!(:text => "Why am I sticky? ________", :blanks => 1)
Question.create!(:text => "Why can't I sleep at night? ________", :blanks => 1)
Question.create!(:text => "Why do I hurt all over? ________", :blanks => 1)
